# Generated by Django 4.1 on 2022-09-05 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantas', '0002_remove_plant_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
