# Generated by Django 4.1 on 2022-09-05 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_plant_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
