# Generated by Django 4.1 on 2022-09-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_plant_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='data_cadastro',
            new_name='ultima_modificacao',
        ),
    ]
