# Generated by Django 4.1 on 2022-09-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_rename_data_cadastro_plant_ultima_modificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='ultima_modificacao',
            new_name='last_modf',
        ),
    ]
